# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://anicolae.ro'
baseurl: ''
title: 'Andrei-Mihai Nicolae'
permalink: pretty
logo: '/assets/logo.png'

# Custom styles
styles:
  - /assets/styles.css
  - /assets/custom.css

# Pagination
paginate: 10
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
